apiVersion: "cluster.kurl.sh/v1beta1"
kind: "Installer"
metadata:
  name: "complex"
spec:
  kubernetes:
    version: "latest"
  weave:
    version: "2.8.1"
  rook:
    version: "1.5.9"
    isBlockStorageEnabled: true
    bypassUpgradeWarning: true
  contour:
    version: "latest"
  docker:
    version: "20.10.5"
    daemonConfig: |
      this is a test file with newlines
      and quotes"
      within it
  prometheus:
    version: "0.47.0-15.2.0"
  registry:
    version: "latest"
  ekco:
    version: "latest"
  certManager:
    version: "1.0.3"
  metricsServer:
    version: "0.4.1"
