apiVersion: "cluster.kurl.sh/v1beta1"
kind: "Installer"
metadata:
  name: "latest"
spec:
  kubernetes:
    version: "latest"
  weave:
    version: "latest"
  rook:
    version: "latest"
  contour:
    version: "latest"
  docker:
    version: "latest"
  prometheus:
    version: "latest"
  registry:
    version: "latest"
  ekco:
    version: "latest"
