# This rebuilds a single package from master and uploads to the staging/ folder.
# The cron-rebuild-packages-staging workflow triggers this once for each package.
name: build-package-staging
on:
  repository_dispatch:
    types: [build-package-staging]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
        PKG: ${{ github.event.client_payload.package }}
        KURL_UTIL_IMAGE: replicated/kurl-util:alpha # required if this is the common package
      run: |
        make dist/$PKG

        MD5="$(openssl md5 -binary dist/$PKG | base64)"
        GITSHA="$(git rev-parse HEAD)"
        aws s3 cp dist/$PKG s3://kurl-sh/staging/$PKG \
          --metadata md5="${MD5}",gitsha="${GITSHA}"
